/* !!! Do not manually modify this file in the production stage !!!
 * This file is automatically created by OSDEdit.exe,
 * and used in the production stage.*/

#ifndef __OSD_SOURCE_H
#define __OSD_SOURCE_H

//Custom color index information
#define       PALETTE_R_COLOR_ERROR                   	0xff
#define       PALETTE_R_COLOR_RED                     	0xfe
#define       PALETTE_R_COLOR_GREEN                   	0xfd
#define       PALETTE_R_COLOR_BLUE                    	0xfc
#define       PALETTE_R_COLOR_WHITE                   	0xfb
#define       PALETTE_R_COLOR_BLACK                   	0xfa
#define       PALETTE_R_COLOR_TRANSFER                	0xf9
#define       PALETTE_R_COLOR_TBLACK                  	0xf8
#define       PALETTE_R_COLOR_YELLOW                  	0xf7
#define       PALETTE_R_COLOR_GARY1                   	0xf6
#define       PALETTE_R_COLOR_BLUE1                   	0xf5
#define       PALETTE_R_COLOR_DBLUE                   	0xf4
#define       PALETTE_R_COLOR_BLUE2                   	0xf3
#define       PALETTE_R_COLOR_GARY2                   	0xf2
#define       PALETTE_R_COLOR_GARY3                   	0xf1

//OSD Icon index information
#define       OSD_CLOCKPOWEROFFC                  	0
#define       OSD_CLOCKPOWEROFFE                  	1
#define       OSD_ICONAUBATTERY0                  	2
#define       OSD_ICONAUBATTERY1                  	3
#define       OSD_ICONAUBATTERY2                  	4
#define       OSD_ICONAUBATTERY3                  	5
#define       OSD_ICONAUBATTERY4                  	6
#define       OSD_ICONAUBATTERY5                  	7
#define       OSD_ICONAUDIORECORDSTART            	8
#define       OSD_ICONAUDIORECORDSTOP             	9
#define       OSD_ICONCLOCKRECT1                  	10
#define       OSD_ICONCLOCK_BATTERY0              	11
#define       OSD_ICONCLOCK_BATTERY1              	12
#define       OSD_ICONCLOCK_BATTERY2              	13
#define       OSD_ICONCLOCK_BATTERY3              	14
#define       OSD_ICONCLOCK_BATTERY4              	15
#define       OSD_ICONCLOCK_BATTERY5              	16
#define       OSD_ICONDATE_B0                     	17
#define       OSD_ICONDATE_B1                     	18
#define       OSD_ICONDATE_B2                     	19
#define       OSD_ICONDATE_B3                     	20
#define       OSD_ICONDATE_B4                     	21
#define       OSD_ICONDATE_B5                     	22
#define       OSD_ICONDATE_B6                     	23
#define       OSD_ICONDATE_B7                     	24
#define       OSD_ICONDATE_B8                     	25
#define       OSD_ICONDATE_B9                     	26
#define       OSD_ICONDATE_BD                     	27
#define       OSD_ICONDATE_L0                     	28
#define       OSD_ICONDATE_L1                     	29
#define       OSD_ICONDATE_L2                     	30
#define       OSD_ICONDATE_L3                     	31
#define       OSD_ICONDATE_L4                     	32
#define       OSD_ICONDATE_L5                     	33
#define       OSD_ICONDATE_L6                     	34
#define       OSD_ICONDATE_L7                     	35
#define       OSD_ICONDATE_L8                     	36
#define       OSD_ICONDATE_L9                     	37
#define       OSD_ICONDATE_LD                     	38
#define       OSD_ICONMENUAUDIO                   	39
#define       OSD_ICONMENUBATTERY                 	40
#define       OSD_ICONMENUCLOCK                   	41
#define       OSD_ICONMENUDELALL                  	42
#define       OSD_ICONMENUDELONE                  	43
#define       OSD_ICONMENUEV                      	44
#define       OSD_ICONMENUFORMAT                  	45
#define       OSD_ICONMENUHZ                      	46
#define       OSD_ICONMENUIMAGEQ                  	47
#define       OSD_ICONMENULANGUAGE                	48
#define       OSD_ICONMENULIGHTNORMAL             	49
#define       OSD_ICONMENULOOPRECORD              	50
#define       OSD_ICONMENUMOTION                  	51
#define       OSD_ICONMENUPOWEROFF                	52
#define       OSD_ICONMENURESET                   	53
#define       OSD_ICONMENURESOLUTION              	54
#define       OSD_ICONMENUSCRENNOFF               	55
#define       OSD_ICONMENUSTRAMP                  	56
#define       OSD_ICONMENUTV                      	57
#define       OSD_ICONMENUVERSION                 	58
#define       OSD_ICONMENUVOLUME                  	59
#define       OSD_ICONMENUVOLUME2                 	60
#define       OSD_ICONMTBATTERY0                  	61
#define       OSD_ICONMTBATTERY1                  	62
#define       OSD_ICONMTBATTERY2                  	63
#define       OSD_ICONMTBATTERY3                  	64
#define       OSD_ICONMTBATTERY4                  	65
#define       OSD_ICONMTBATTERY5                  	66
#define       OSD_ICONMTMENU                      	67
#define       OSD_ICONMTMICOFF                    	68
#define       OSD_ICONMTMICON                     	69
#define       OSD_ICONMTMORE                      	70
#define       OSD_ICONMTMOTION                    	71
#define       OSD_ICONMTOFF                       	72
#define       OSD_ICONMTON                        	73
#define       OSD_ICONMTPAUSE                     	74
#define       OSD_ICONMTPHOTO                     	75
#define       OSD_ICONMTPLAY                      	76
#define       OSD_ICONMTPLAY2                     	77
#define       OSD_ICONMTRECORD                    	78
#define       OSD_ICONMTSDCNORMAL                 	79
#define       OSD_ICONMTSDCNULL                   	80
#define       OSD_ICONPICTURE                     	81
#define       OSD_ICONRECASTATE                   	82
#define       OSD_ICONRECSTATE                    	83
#define       OSD_ICONWEEK_EN_FRI                 	84
#define       OSD_ICONWEEK_EN_MON                 	85
#define       OSD_ICONWEEK_EN_SAT                 	86
#define       OSD_ICONWEEK_EN_SUN                 	87
#define       OSD_ICONWEEK_EN_THUR                	88
#define       OSD_ICONWEEK_EN_TUE                 	89
#define       OSD_ICONWEEK_EN_WED                 	90
#define       OSD_ICONWEEK_JA_FRI                 	91
#define       OSD_ICONWEEK_JA_MON                 	92
#define       OSD_ICONWEEK_JA_SAT                 	93
#define       OSD_ICONWEEK_JA_SUN                 	94
#define       OSD_ICONWEEK_JA_THUR                	95
#define       OSD_ICONWEEK_JA_TUE                 	96
#define       OSD_ICONWEEK_JA_WED                 	97
#define       OSD_ICONWEEK_KO_FRI                 	98
#define       OSD_ICONWEEK_KO_MON                 	99
#define       OSD_ICONWEEK_KO_SAT                 	100
#define       OSD_ICONWEEK_KO_SUN                 	101
#define       OSD_ICONWEEK_KO_THUR                	102
#define       OSD_ICONWEEK_KO_TUE                 	103
#define       OSD_ICONWEEK_KO_WED                 	104
#define       OSD_ICONWEEK_SC_FRI                 	105
#define       OSD_ICONWEEK_SC_MON                 	106
#define       OSD_ICONWEEK_SC_SAT                 	107
#define       OSD_ICONWEEK_SC_SUN                 	108
#define       OSD_ICONWEEK_SC_THUR                	109
#define       OSD_ICONWEEK_SC_TUE                 	110
#define       OSD_ICONWEEK_SC_WED                 	111
#define       OSD_MIC                             	112
#define       OSD_NAME0_P                         	113
#define       OSD_NAME1_P                         	114
#define       OSD_NAME2_P                         	115
#define       OSD_NAME3_P                         	116
#define       OSD_NAME4_P                         	117
#define       OSD_NAME5_P                         	118
#define       OSD_NAME6_P                         	119
#define       OSD_NAME7_P                         	120
#define       OSD_NAME8_P                         	121
#define       OSD_NAME9_P                         	122
#define       OSD_TIME0_P                         	123
#define       OSD_TIME1_P                         	124
#define       OSD_TIME2_P                         	125
#define       OSD_TIME3_P                         	126
#define       OSD_TIME4_P                         	127
#define       OSD_TIME5_P                         	128
#define       OSD_TIME6_P                         	129
#define       OSD_TIME7_P                         	130
#define       OSD_TIME8_P                         	131
#define       OSD_TIME9_P                         	132
#define       OSD_TIME_P                          	133
#define       OSD_WAV                             	134


#endif
