/* !!! Do not manually modify this file in the production stage !!!
 * This file is automatically created by MakeResBin.exe,
 * and used in the production stage.*/

#ifndef __RES_H_
#define __RES_H_

#define         RES_ICON_PCCAM_MODE     	0
#define         RES_ICON_POWER_OFF      	1
#define         RES_ICON_POWER_ON       	2
#define         RES_OSD_SOURCE          	3
#define         RES_PALETTE             	4
#define         RES_RESFONT             	5
#define         RES_RESFONTIDX          	6
#define         RES_STR_VERSION         	7

#endif
